load('Preprocessed');
LogisticRegressionFinalFeaturePrep;

observations_all_nonstd = [feature0, fipsOutcome,femaleOutcome,maleOutcome,whiteOutcome,blackOutcome,...
    hispanicOutcome, asianOutcome,raceOtherOutcome,speedingOutcome,movingViolationOutcome, ...
    lightsOutcome, registrationPlatesOutcome, safeMovementOutcome, cellPhoneOutcome, seatBeltOutcome, ...
    violationOtherOutcome, age1625Outcome, age2635Outcome, age3645Outcome, age4655Outcome, age5665Outcome, ...
    age6675Outcome, age7685Outcome, ageAbove86Outcome, stopDuration115Outcome, stopDuration1630Outcome, stopDuration30plusOutcome];
observationsTEST_nonstd = observations_all_nonstd(numtrain+numdev+1:numtrain+numdev+numtest,:);
observationsTRAIN_nonstd = observations_all_nonstd(1:numtrain,:);
observationsTEST_std = observationsTEST;